# Generated by Django 2.0.2 on 2018-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('placa', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='')),
                ('horasVuelo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('numSerie', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=200)),
                ('fechaFabricacion', models.DateField()),
                ('proveedor', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('horasUtil', models.CharField(max_length=200)),
                ('fechaVencimiento', models.DateField()),
                ('horasVuelo', models.CharField(max_length=200)),
                ('ingreso', models.DateField()),
                ('estado', models.CharField(max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cumplimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCumplimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('titulo', models.TextField()),
                ('metoCumplimiento', models.TextField()),
                ('metoInspeccion', models.CharField(max_length=200)),
                ('proximo', models.CharField(max_length=200)),
                ('tecnico', models.CharField(max_length=200)),
                ('inspector', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('horaDespegue', models.CharField(max_length=200)),
                ('horaAterrizaje', models.CharField(max_length=200)),
            ],
        ),
    ]
