# Generated by Django 2.0.2 on 2018-11-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componente',
            options={'ordering': ['-creado'], 'verbose_name': 'Componente', 'verbose_name_plural': 'Componentes'},
        ),
        migrations.AddField(
            model_name='aeronave',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aeronave',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cumplimiento',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cumplimiento',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcumplimiento',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemcumplimiento',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='imagen',
            field=models.ImageField(upload_to='Aeronave'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='componente',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='estado',
            field=models.CharField(max_length=200, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='fabricante',
            field=models.CharField(max_length=200, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='fechaFabricacion',
            field=models.DateField(verbose_name='Fecha de Fabricacion'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='fechaVencimiento',
            field=models.DateField(verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='horasUtil',
            field=models.CharField(max_length=200, verbose_name='Horas de vida util'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='horasVuelo',
            field=models.CharField(max_length=200, verbose_name='Horas de Vuelo'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='ingreso',
            field=models.DateField(verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='marca',
            field=models.CharField(max_length=200, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='numSerie',
            field=models.CharField(max_length=200, verbose_name='Numero de Serie'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='proveedor',
            field=models.CharField(max_length=200, verbose_name='Proveedor'),
        ),
    ]
