# Generated by Django 2.0.2 on 2018-11-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0002_auto_20181122_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='hUtilizado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas utilizado'),
        ),
        migrations.AddField(
            model_name='componente',
            name='hvUtil',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas de vida util'),
        ),
        migrations.AddField(
            model_name='componente',
            name='mUtilizado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minutos utilizado'),
        ),
        migrations.AddField(
            model_name='componente',
            name='mvUtil',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minutos de vida util'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='componente',
            name='horasVuelo',
            field=models.CharField(max_length=200, verbose_name='Horas Utilizado'),
        ),
    ]
