# Generated by Django 2.0.2 on 2018-11-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0003_auto_20181126_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aeronave',
            options={'ordering': ['-creado'], 'verbose_name': 'Aeronave', 'verbose_name_plural': 'Aeronaves'},
        ),
        migrations.AddField(
            model_name='aeronave',
            name='Componentes',
            field=models.ManyToManyField(blank=True, to='aerolinea.Componente', verbose_name='Componentes'),
        ),
        migrations.AddField(
            model_name='aeronave',
            name='mVuelo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minutos de Vuelo'),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='horasVuelo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas de Vuelo'),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='imagen',
            field=models.ImageField(upload_to='Aeronave', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='marca',
            field=models.CharField(max_length=200, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='modelo',
            field=models.CharField(max_length=200, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='placa',
            field=models.CharField(max_length=200, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='tipo',
            field=models.CharField(max_length=200, verbose_name='Tipo'),
        ),
    ]
