# Generated by Django 2.0.2 on 2018-11-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0004_auto_20181126_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aeronave',
            old_name='horasVuelo',
            new_name='hVuelo',
        ),
        migrations.RenameField(
            model_name='componente',
            old_name='ingreso',
            new_name='fechaingreso',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='horasUtil',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='horasVuelo',
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='Componentes',
            field=models.ManyToManyField(to='aerolinea.Componente', verbose_name='Componentes'),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
