# Generated by Django 2.0.2 on 2018-11-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0005_auto_20181127_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aeronave',
            old_name='Componentes',
            new_name='componentes',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='horaAterrizaje',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='horaDespegue',
        ),
        migrations.AddField(
            model_name='vuelo',
            name='horas',
            field=models.CharField(max_length=200, null=True, verbose_name='Horas de vuelo'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='minutos',
            field=models.CharField(max_length=200, null=True, verbose_name='Minutos de vuelo'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='observaciones',
            field=models.TextField(null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='destino',
            field=models.CharField(max_length=200, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de vuelo'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='origen',
            field=models.CharField(max_length=200, verbose_name='Origen'),
        ),
    ]
