# Generated by Django 2.0.2 on 2018-11-28 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0006_auto_20181127_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeronave',
            name='componentes',
        ),
        migrations.AddField(
            model_name='aeronave',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aerolinea.Componente', verbose_name='Componentes'),
        ),
    ]
