# Generated by Django 2.0.2 on 2018-11-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0007_auto_20181128_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeronave',
            name='componente',
        ),
        migrations.AddField(
            model_name='aeronave',
            name='componente',
            field=models.ManyToManyField(blank=True, null=True, to='aerolinea.Componente', verbose_name='Componentes'),
        ),
    ]
