# Generated by Django 2.0.2 on 2018-11-28 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0008_auto_20181128_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='aeronave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aerolinea.Aeronave'),
        ),
    ]
