# Generated by Django 2.0.2 on 2018-12-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0010_auto_20181128_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronave',
            name='componente',
            field=models.ManyToManyField(blank=True, to='aerolinea.Componente', verbose_name='Componentes'),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='aeronave',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Aeronave', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='hDurg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas Durg'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='hRemanente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas Remanente'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mDurg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minutos Durg'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mRemanente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minutos Remanente'),
        ),
    ]
