# Generated by Django 2.0.2 on 2018-12-09 02:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0011_auto_20181204_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
    ]
