# Generated by Django 2.0.2 on 2018-12-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0012_auto_20181208_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='horas',
            field=models.IntegerField(null=True, verbose_name='Horas de vuelo'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='minutos',
            field=models.IntegerField(null=True, verbose_name='Minutos de vuelo'),
        ),
    ]
