# Generated by Django 2.0.2 on 2018-12-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0013_auto_20181220_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('fecha', models.DateField(verbose_name='Fecha de Orden')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('tecnico', models.CharField(max_length=200, verbose_name='Tecnico')),
                ('dirCC', models.CharField(max_length=200, verbose_name='Director control calidad')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.Aeronave', verbose_name='Aeronave')),
                ('componente', models.ManyToManyField(blank=True, to='aerolinea.Componente', verbose_name='Componente(s)')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'ordering': ['-creado'],
            },
        ),
    ]
