# Generated by Django 2.0.2 on 2019-01-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0015_auto_20190115_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeronave',
            name='placa',
            field=models.CharField(max_length=200, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion'),
        ),
    ]
