# Generated by Django 2.0.2 on 2019-01-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0016_auto_20190121_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='vUtilOpc',
            field=models.CharField(choices=[('h', 'Horas'), ('t', 'Tiempo'), ('a', 'Ambos')], default='h', max_length=20, verbose_name='Vida Util'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='hvUtil',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Horas de vida util'),
        ),
    ]
