# Generated by Django 2.0.2 on 2019-01-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0017_auto_20190121_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='marca',
            field=models.CharField(max_length=200, verbose_name='Marca /P-N o Modelo'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='vUtil',
            field=models.DateField(verbose_name='Vida Util Calendario'),
        ),
    ]
