# Generated by Django 2.0.2 on 2019-01-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0020_auto_20190122_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='vUtil',
            field=models.DateField(blank=True, verbose_name='Vida Util Calendario'),
        ),
    ]
