# Generated by Django 2.0.2 on 2019-01-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0022_auto_20190122_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='ordenCom',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Orden componentes'),
        ),
    ]
