# Generated by Django 2.0.2 on 2019-02-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0024_auto_20190201_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='porcenUso',
            field=models.IntegerField(default=1, verbose_name='Porcentaje de uso'),
        ),
    ]
