# Generated by Django 2.0.2 on 2019-02-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0026_auto_20190205_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='alertaFecha',
            field=models.CharField(default='No', max_length=20, verbose_name='Alerta fecha'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='fechaingreso',
            field=models.DateField(verbose_name='Fecha de Instalacion'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
