# Generated by Django 2.0.2 on 2019-02-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0027_auto_20190207_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='ordenTrabajo',
            field=models.CharField(default='777', max_length=20, verbose_name='Orden Trabajo'),
        ),
    ]
