# Generated by Django 2.0.2 on 2019-02-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0028_componente_ordentrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='fechaFabricacion',
            field=models.DateField(null=True, verbose_name='Fecha de Fabricacion'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='hUtilizado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas total'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='hvUtil',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Horas TBO'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mUtilizado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minutos total'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='marca',
            field=models.CharField(max_length=200, verbose_name='Parte/Numero'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mvUtil',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minutos TBO'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='vUtil',
            field=models.DateField(blank=True, null=True, verbose_name='TBO Calendario'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='vUtilOpc',
            field=models.CharField(choices=[('h', 'Horas'), ('t', 'Tiempo'), ('a', 'Ambos')], default='h', max_length=20, verbose_name='TBO'),
        ),
    ]
