# Generated by Django 2.0.2 on 2019-02-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0029_auto_20190214_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='mesesVencimiento',
            field=models.IntegerField(default=1, verbose_name='Meses de vencimiento'),
        ),
    ]
