# Generated by Django 2.0.2 on 2019-02-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0030_componente_mesesvencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='estado',
            field=models.CharField(max_length=200, null=True, verbose_name='Estado'),
        ),
    ]
