# Generated by Django 2.0.2 on 2019-02-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0033_auto_20190215_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='hvUtil_p',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Horas inspec posterior TBO'),
        ),
        migrations.AddField(
            model_name='componente',
            name='tipo',
            field=models.CharField(choices=[('t1', 'Tipo 1'), ('t2', 'Tipo 2')], default='t1', max_length=20, verbose_name='TBO'),
        ),
        migrations.AddField(
            model_name='componente',
            name='vUtilOpc_p',
            field=models.CharField(choices=[('h', 'Horas'), ('t', 'Tiempo'), ('a', 'Ambos')], default='h', max_length=20, null=True, verbose_name='TBO inspeccion posterior'),
        ),
        migrations.AddField(
            model_name='componente',
            name='vUtil_p',
            field=models.DateField(blank=True, null=True, verbose_name='TBO Calendario inspec posterior'),
        ),
    ]
