# Generated by Django 2.0.2 on 2019-02-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0034_auto_20190215_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='tipo',
            field=models.CharField(choices=[('t1', 'Tipo 1'), ('t2', 'Tipo 2')], default='t1', max_length=20, null=True, verbose_name='TBO'),
        ),
    ]
