# Generated by Django 2.0.2 on 2019-02-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0035_auto_20190215_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='tipo',
            field=models.CharField(choices=[('t1', 'Tipo 1'), ('t2', 'Tipo 2')], default='t1', max_length=20, null=True, verbose_name='Tipo componente'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='vUtilOpc',
            field=models.CharField(choices=[('h', 'Horas'), ('t', 'Tiempo'), ('a', 'Ambos')], default='h', max_length=20, null=True, verbose_name='TBO'),
        ),
    ]
