# Generated by Django 2.0.2 on 2019-02-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0036_auto_20190215_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='vUtilOpc',
            field=models.CharField(blank=True, choices=[('h', 'Horas'), ('t', 'Tiempo'), ('a', 'Ambos')], default='h', max_length=20, null=True, verbose_name='TBO'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='vUtilOpc_i',
            field=models.CharField(blank=True, choices=[('h', 'Horas'), ('t', 'Tiempo'), ('a', 'Ambos')], default='h', max_length=20, null=True, verbose_name='TBO inspeccion inicial'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='vUtilOpc_p',
            field=models.CharField(blank=True, choices=[('h', 'Horas'), ('t', 'Tiempo'), ('a', 'Ambos')], default='h', max_length=20, null=True, verbose_name='TBO inspeccion posterior'),
        ),
    ]
