# Generated by Django 2.0.2 on 2019-02-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0037_auto_20190215_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='hDurg',
            field=models.IntegerField(default=1, verbose_name='Horas Durg'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='hRemanente',
            field=models.IntegerField(default=1, verbose_name='Horas Remanente'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='hUtilizado',
            field=models.IntegerField(default=1, verbose_name='Horas total'),
        ),
    ]
