# Generated by Django 2.0.2 on 2019-02-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0038_auto_20190218_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='mvUtil_i',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Minutos inspec inicial TBO'),
        ),
        migrations.AddField(
            model_name='componente',
            name='mvUtil_p',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Minutos inspec posterior TBO'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mvUtil',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Minutos TBO'),
        ),
    ]
