# Generated by Django 2.0.2 on 2019-02-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0039_auto_20190226_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='hRemanente_i',
            field=models.IntegerField(default=1, verbose_name='Horas Remanente inicial'),
        ),
        migrations.AddField(
            model_name='componente',
            name='hRemanente_p',
            field=models.IntegerField(default=1, verbose_name='Horas Remanente posterior'),
        ),
        migrations.AddField(
            model_name='componente',
            name='porcenUso_i',
            field=models.IntegerField(default=1, verbose_name='Porcentaje de uso inicial'),
        ),
        migrations.AddField(
            model_name='componente',
            name='porcenUso_p',
            field=models.IntegerField(default=1, verbose_name='Porcentaje de uso posterior'),
        ),
    ]
