# Generated by Django 2.0.2 on 2019-02-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0040_auto_20190227_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='mRemanente_i',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Minutos Remanente inicial'),
        ),
        migrations.AddField(
            model_name='componente',
            name='mRemanente_p',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Minutos Remanente posterior'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='hvUtil',
            field=models.IntegerField(default=1, verbose_name='Horas TBO'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='hvUtil_i',
            field=models.IntegerField(default=1, verbose_name='Horas inspec inicial TBO'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='hvUtil_p',
            field=models.IntegerField(default=1, verbose_name='Horas inspec posterior TBO'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mDurg',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Minutos Durg'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mRemanente',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Minutos Remanente'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mUtilizado',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Minutos total'),
        ),
    ]
