# Generated by Django 2.0.2 on 2019-02-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0041_auto_20190227_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='alertaFecha_i',
            field=models.CharField(default='No', max_length=20, verbose_name='Alerta fecha inicial'),
        ),
        migrations.AddField(
            model_name='componente',
            name='alertaFecha_p',
            field=models.CharField(default='No', max_length=20, verbose_name='Alerta fecha posterior'),
        ),
        migrations.AddField(
            model_name='componente',
            name='alerta_i',
            field=models.CharField(default='No', max_length=20, verbose_name='Alerta inicial'),
        ),
        migrations.AddField(
            model_name='componente',
            name='alerta_p',
            field=models.CharField(default='No', max_length=20, verbose_name='Alerta posterior'),
        ),
    ]
