# Generated by Django 2.0.2 on 2019-02-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0042_auto_20190227_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='mDurg',
            field=models.IntegerField(default=1, verbose_name='Minutos Durg'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mRemanente',
            field=models.IntegerField(default=1, verbose_name='Minutos Remanente'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mRemanente_i',
            field=models.IntegerField(default=1, verbose_name='Minutos Remanente inicial'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mRemanente_p',
            field=models.IntegerField(default=1, verbose_name='Minutos Remanente posterior'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mUtilizado',
            field=models.IntegerField(default=1, verbose_name='Minutos total'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mvUtil',
            field=models.IntegerField(default=1, verbose_name='Minutos TBO'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mvUtil_i',
            field=models.IntegerField(default=1, verbose_name='Minutos inspec inicial TBO'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mvUtil_p',
            field=models.IntegerField(default=1, verbose_name='Minutos inspec posterior TBO'),
        ),
    ]
