# Generated by Django 2.0.2 on 2019-03-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0043_auto_20190227_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='hDurg',
            field=models.IntegerField(blank=True, default=1, verbose_name='Horas Durg'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='hUtilizado',
            field=models.IntegerField(blank=True, default=1, verbose_name='Horas total'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='hvUtil',
            field=models.IntegerField(blank=True, default=1, verbose_name='Horas TBO'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='hvUtil_i',
            field=models.IntegerField(blank=True, default=1, verbose_name='Horas inspec inicial TBO'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='hvUtil_p',
            field=models.IntegerField(blank=True, default=1, verbose_name='Horas inspec posterior TBO'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mDurg',
            field=models.IntegerField(blank=True, default=1, verbose_name='Minutos Durg'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mUtilizado',
            field=models.IntegerField(blank=True, default=1, verbose_name='Minutos total'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mvUtil',
            field=models.IntegerField(blank=True, default=1, verbose_name='Minutos TBO'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mvUtil_i',
            field=models.IntegerField(blank=True, default=1, verbose_name='Minutos inspec inicial TBO'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='mvUtil_p',
            field=models.IntegerField(blank=True, default=1, verbose_name='Minutos inspec posterior TBO'),
        ),
    ]
