# Generated by Django 2.0.2 on 2019-03-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0044_auto_20190306_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='mesesVencimiento',
            field=models.IntegerField(blank=True, default=1, verbose_name='Meses de vencimiento'),
        ),
    ]
